scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala
Fix typo in parameter name.
s/Partiton/Partition/
=> Fix typo in parameter name.

scripts/sparkclr-submit.cmd
SPARKCLR_JAR should be spark-clr-1.4.1-SNAPSHOT.jar
=>  Fix the bug that wrong SPARKCLR_JAR is specified in sparkclr-submit.cmd

README.md, csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs, csharp/Adapter/Microsoft.Spark.CSharp/Core/SparkContext.cs, scala/pom.xml, scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala, scala/src/main/org/apache/spark/deploy/csharp/CSharpRunner.scala, scala/src/main/org/apache/spark/launcher/SparkCLRSubmitArguments.scala, scala/src/main/org/apache/spark/util/csharp/Utils.scala, scala/src/test/resources/org/apache/spark/launcher/Test.txt, scala/src/test/scala/org/apache/spark/csharp/SparkCLRFunSuite.scala, scala/src/test/scala/org/apache/spark/launcher/SparkCLRSubmitArgumentsSuite.scala, scala/src/test/scala/org/apache/spark/util/csharp/UtilsSuite.scala, scripts/sparkclr-submit.cmd
In this PR, we made some modifications to job submission, now submission cmd line is more concise and zip is supported. Please refer to README.md to get more details.
=> Simplified job submission & Zip support

csharp/Samples/Microsoft.Spark.CSharp/DStreamSamples.cs
it's a minor change in a streaming sample, would like code review on PR directly
=> improve DStreamSample's synchronization of C# and Java to let StreamingContext stop gracefully

scala/src/test/scala/org/apache/spark/launcher/SparkCLRSubmitArgumentsSuite.scala
1. Add two test cases to make sure `SPARKCSV_JARS` is processed correctly. 
2. Remove temp file "Test*.exe" after UT finish.
=> Add unit tests for env variable `SPARKCSV_JARS` is not supported issue.

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IDataFrameProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/DataFrameIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrame.cs, csharp/Samples/Microsoft.Spark.CSharp/DataFrameSamples.cs
* Add `Head()`, `First()`, `Take(n)` and `Distinct()`.
* Add samples and validation for the new-added API.
=> DataFrame API: `Head()`, `First()`, `Take(n)` and `Distinct()`

Build.cmd, RunSamples.cmd, csharp/Samples/Microsoft.Spark.CSharp/DataFrameSamples.cs, scripts/zipdir.ps1
(1) zip run directory; run.zip is located under target;
(2) Fix compiler warning in DataFrameSample.cs as well
=> update build.cmd to clean first before build, and etc.

csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrame.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/Row.cs, csharp/Samples/Microsoft.Spark.CSharp/DataFrameSamples.cs
* Add `DataFrame.Rdd`
* Add samples & validation for `DataFrame.Rdd`
=> Add DataFrame API: DataFrame.Rdd

csharp/AdapterTest/DataFrameTest.cs
Reset mockDataFrameProxy before execute `Sample` methold
=> Fix UT TestSample failed issue

Build.cmd, scala/other-plugin.xml, scala/pom.xml, scripts/addotherplugin.ps1
Without breaking debug mode in IntelliJ
=> workaround to build uber pacakge in build.cmd using shade-plugin

csharp/AdapterTest/DataFrameTest.cs
* Add unit tests for DataFrame API: `First`, `Head`, `Limit`, `Take` and `Distinct`
* Extract two helper methods `MockDataFrameProxyForCollect` and `AssertRow` for easy UT implementation.
=> Add unit tests for DataFrame API: First, Head, Limit, Take and Distinct

appveyor.yml, csharp/AdapterTest/AdapterTest.csproj, csharp/AdapterTest/ComparableRDDTest.cs, csharp/AdapterTest/DataFrameTest.cs, csharp/AdapterTest/DoubleRDDTest.cs, csharp/AdapterTest/PairRDDTest.cs, csharp/AdapterTest/RDDTest.cs, csharp/AdapterTest/SparkCLRTestEnvironment.cs, csharp/AdapterTest/packages.config, csharp/Samples/Microsoft.Spark.CSharp/Samples.csproj, csharp/Samples/Microsoft.Spark.CSharp/packages.config
Reverts Microsoft/SparkCLR#136
=> Revert "Update to nunit3 as appveyor is upgraded"

appveyor.yml, csharp/AdapterTest/AdapterTest.csproj, csharp/AdapterTest/ComparableRDDTest.cs, csharp/AdapterTest/DataFrameTest.cs, csharp/AdapterTest/DoubleRDDTest.cs, csharp/AdapterTest/PairRDDTest.cs, csharp/AdapterTest/RDDTest.cs, csharp/AdapterTest/SparkCLRTestEnvironment.cs, csharp/AdapterTest/packages.config, csharp/Samples/Microsoft.Spark.CSharp/Samples.csproj, csharp/Samples/Microsoft.Spark.CSharp/packages.config
This reverts commit e2bc271edb9174dbdb1f95c1438c60f2350a4d70.
=> Update to nunit3 as appveyor is upgraded

csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj, csharp/Adapter/Microsoft.Spark.CSharp/Properties/AssemblyInfo.cs, csharp/AdapterTest/AdapterTest.csproj, csharp/AdapterTest/Properties/AssemblyInfo.cs, csharp/Samples/Microsoft.Spark.CSharp/Properties/AssemblyInfo.cs, csharp/Samples/Microsoft.Spark.CSharp/Samples.csproj, csharp/SparkCLR.nuspec, csharp/Worker/Microsoft.Spark.CSharp/Properties/AssemblyInfo.cs, csharp/Worker/Microsoft.Spark.CSharp/Worker.csproj, scala/pom.xml
to prepare for the release later
=> added back AssemblyInfo.cs for version stamps

Build.cmd, csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IDataFrameProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IDataFrameWriterProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/DataFrameIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/DataFrameWriterIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrame.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrameWriter.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/SaveMode.cs, csharp/AdapterTest/AdapterTest.csproj, csharp/AdapterTest/DataFrameTest.cs, csharp/AdapterTest/DataFrameWriterTest.cs, csharp/AdapterTest/Mocks/MockDataFrameProxy.cs, csharp/Samples/Microsoft.Spark.CSharp/CommandlineArgumentProcessor.cs, csharp/Samples/Microsoft.Spark.CSharp/DataFrameSamples.cs, csharp/Samples/Microsoft.Spark.CSharp/SamplesRunner.cs
* Add `DataFrame.Write()` API
* Add `DataFrameWriter` class
* New API Samples:
* `DataFrame.Write()` sample.
* DataFrame accumulator sample.
* Unit tests
* Minor fix for `RunSamples.cmd` and `SampleRunner.cs`
=> Add DataFrame.Write() API

csharp/SparkCLR.nuspec, csharp/build.sh
This is to ensure nuget package can be used to compile C# drive program. Tested with all samples.
=> include dependent packages, symbols and config files

csharp/WorkerTest/WorkerTest.csproj, csharp/WorkerTest/packages.config
- Missing NuGet package reference for nunit package.
=> Add missing packages.config reference in WorkerTest project.

downloadtools.ps1
When execute `RunSamples.cmd` for the first time on Windows, `RunSamples.cmd` will try to download all runtime dependencies. For dependencies like `spark-1.5.2-bin-hadoop2.6.tgz`, the file size is kind of large.
During downloading, for now user can't know how is the downloading going. Sometimes user might get confused as there is no response before downloading completes(especially when the internet connection is not good enough).
This PR tries to show progress bar when downloading files.
=> Show progress bar when downloading runtime dependencies

appveyor.yml
Use Branch 1.4 to validate deployment to Github releases
=> updated appveyor.yml to validate deploy to GitHub Release

appveyor.yml, csharp/Build.cmd, scripts/nugetpack.ps1
update nuget publish to include symbols
=> Branch 1.4

csharp/WorkerTest/WorkerTest.cs, csharp/WorkerTest/WorkerTest.csproj
Add more test cases to `Worker.cs` to improve the UT coverage.
=> Add unit tests to Worker.cs

examples/Examples.sln, examples/JdbcDataFrame/App.config, examples/JdbcDataFrame/JdbcDataFrame.csproj, examples/JdbcDataFrame/Program.cs, examples/JdbcDataFrame/Properties/AssemblyInfo.cs, examples/JdbcDataFrame/packages.config
There was a post in StackOverflow asking for using JDBC API in SparkCLR. http://stackoverflow.com/questions/34494502/accessing-sql-server-data-into-sparkclr/34688154#34688154. Using the code from the post to create a new example.
=> adding JDBC example to DataFrame API

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs, csharp/Worker/Microsoft.Spark.CSharp/Worker.cs
Kept rdd and latency logging as INFO.
=> move verbose log from INFO to DEBUG

csharp/AdapterTest/PayloadHelperTest.cs
@jthelin gave a great comment on test case `PayloadHelperTest`. 
https://github.com/Microsoft/SparkCLR/pull/246/files#r49744452
This PR follows his suggestion to add some negative values for check in PayloadHelperTest.
=> Add some negative values for check in PayloadHelperTest

csharp/WorkerTest/WorkerTest.cs
=> Fix R# Unit Tests error when shadow copying is enabled

csharp/Adapter/Microsoft.Spark.CSharp/Sql/Functions.cs, csharp/AdapterTest/FunctionsTest.cs
Issue #281 
My first PR ever. Let me know if something's wrong. I ran all the tests and samples.
=> Changed deprecated camelCase SQL function names to underscore format

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IStreamingContextProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/Kafka.cs, csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML, csharp/AdapterTest/Mocks/MockStreamingContextProxy.cs, csharp/AdapterTest/StreamingContextTest.cs, scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaCluster.scala, scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaInputDStream.scala, scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaRDD.scala, scala/src/main/org/apache/spark/streaming/api/kafka/KafkaUtilsCSharpHelper.scala
customizing KafkaUtils using inheritance model with dynamic kafka rdd partitioning and kafka read fault tolerance. no automated tests yet
=> add new API DirectKafkaStreamWithRepartition manual test only in Sandbox

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs, csharp/Adapter/Microsoft.Spark.CSharp/Core/Accumulator.cs, csharp/Adapter/Microsoft.Spark.CSharp/Core/Broadcast.cs, csharp/Adapter/Microsoft.Spark.CSharp/Core/DoubleRDDFunctions.cs, csharp/Adapter/Microsoft.Spark.CSharp/Core/Option.cs, csharp/Adapter/Microsoft.Spark.CSharp/Core/OrderedRDDFunctions.cs, csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML, csharp/Adapter/documentation/Mobius_API_Documentation.md
Add XML comments to fix the build warnings in the 5 files below:
ConfigurationService.cs
Accumulator.cs
Broadcast.cs
DoubleRDDFunctions.cs
Option.cs
OrderedRDDFunctions.cs
=> Fix build warning (part 1): Add XML comments for Csharp classes

csharp/Adapter/Microsoft.Spark.CSharp/Core/PipelinedRDD.cs, csharp/Adapter/Microsoft.Spark.CSharp/Core/Profiler.cs, csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/IJvmBridge.cs, csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/JvmBridge.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/Types.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/PairDStreamFunctions.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/StreamingContext.cs, csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML, csharp/Adapter/documentation/Mobius_API_Documentation.md
Add XML comments for PipelinedRDD,Profiler,IJvmBridge,JvmBridge,Types,PairDStreamFunctions,StreamingContext.
=> Fix Build Warnings (part 3): Add XML comments for CSharp code

examples/Examples.sln, examples/WordCount/App.config, examples/WordCount/Program.cs, examples/WordCount/Properties/AssemblyInfo.cs, examples/WordCount/WordCount.csproj, examples/WordCount/packages.config, notes/running-mobius-app.md
Need a wordcount example similar to https://github.com/apache/spark/blob/master/examples/src/main/python/wordcount.py
=> https://github.com/Microsoft/Mobius/issues/267

csharp/Adapter/Microsoft.Spark.CSharp/Core/StorageLevel.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/Column.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/RowConstructor.cs, csharp/Adapter/Microsoft.Spark.CSharp/Sql/SaveMode.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/Kafka.cs, csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML, csharp/Adapter/documentation/Mobius_API_Documentation.md
Add XML comments for StorageLevel, Column, RowConstructor, SaveMode, Kafka
=> Fix Build Warnings (part 4): Add XML comments for Csharp code

scala/src/main/org/apache/spark/api/csharp/CSharpBackend.scala, scala/src/main/org/apache/spark/api/csharp/CSharpBackendHandler.scala
Make CSharpBackendHandler thread safe
=> Make CSharpBackendHandler thread safe

csharp/AdapterTest/ColumnTest.cs, csharp/AdapterTest/DataFrameNaFunctionsTest.cs, csharp/AdapterTest/DataFrameTest.cs, csharp/AdapterTest/FunctionsTest.cs, csharp/AdapterTest/Mocks/MockDataFrameProxy.cs, csharp/AdapterTest/RowTest.cs, csharp/AdapterTest/SqlContextTest.cs, csharp/Tests.Common/RowHelper.cs
Add more Unit test for Columns.cs,DataFrame.cs,Types.cs,DataFrameNaFunctions.cs,Functions.cs
=> Improve unit test coverage in "Sql" namespace(Part 2)

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs, csharp/AdapterTest/ConfigurationServiceTest.cs, scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala, scala/src/main/org/apache/spark/util/csharp/Utils.scala, scala/src/test/scala/org/apache/spark/util/csharp/UtilsSuite.scala
This PR mainly contains two changes for Linux:
1. Fix CSharpWorker path, by adding "./"
2. Preserve file permissions when doing zip & unzip dependencies
=> Fix for issue #285

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs, csharp/AdapterTest/ConfigurationServiceTest.cs, scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala, scala/src/main/org/apache/spark/util/csharp/Utils.scala
1. construct csharp worker path in CSharpRDD.compute; 
2. set unix mode in zip files for cross-platform supports
=> Fix for issue #460

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs, csharp/AdapterTest/ConfigurationServiceTest.cs, scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala, scala/src/main/org/apache/spark/util/csharp/Utils.scala
1. construct csharp worker path in CSharpRDD.compute;
2. set unix mode in zip files for cross-platform supports
=> Fix for issue #460 in Branch 1.6

.gitignore, csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj, csharp/Adapter/Microsoft.Spark.CSharp/Core/Accumulator.cs, csharp/Adapter/Microsoft.Spark.CSharp/Core/RDDCollector.cs, csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/JvmBridge.cs, csharp/Adapter/Microsoft.Spark.CSharp/Network/DefaultSocketWrapper.cs, csharp/Adapter/Microsoft.Spark.CSharp/Network/ISocketWrapper.cs, csharp/Adapter/Microsoft.Spark.CSharp/Network/SocketFactory.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs, csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML, csharp/Adapter/documentation/Mobius_API_Documentation.md, csharp/AdapterTest/AccumulatorTest.cs, csharp/AdapterTest/Mocks/MockSparkContextProxy.cs, csharp/AdapterTest/TestWithMoqDemo.cs, csharp/Worker/Microsoft.Spark.CSharp/MultiThreadWorker.cs, csharp/Worker/Microsoft.Spark.CSharp/TaskRunner.cs, csharp/Worker/Microsoft.Spark.CSharp/Worker.cs, csharp/WorkerTest/MultiThreadWorkerTest.cs, csharp/WorkerTest/WorkerTest.cs
Wrap System.Net.Sockets.Socket class to DefaultSocketWrapper with ISocketWrapper.
=> Add a wrapper for Socket interface

README.md, notes/running-mobius-app.md
This is just the initial draft of doc. It needs to be updated once #467 and #468 are fixed
=> adding instructions for Linux

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IStreamingContextProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/StreamingContext.cs, csharp/AdapterTest/Mocks/MockStreamingContextProxy.cs, csharp/AdapterTest/StreamingContextTest.cs
Fix AwaitTermination(int timeout) error, and change to AwaitTerminationOrTimeout(long timeout).
=> Fix AwaitTermination(int timeout) error

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IStreamingContextProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/Kafka.cs, csharp/AdapterTest/Mocks/MockStreamingContextProxy.cs, csharp/AdapterTest/StreamingContextTest.cs, csharp/WorkerTest/WorkerTest.cs, notes/configuration-mobius.md, scala/src/main/org/apache/spark/streaming/api/csharp/CSharpDStream.scala, scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaInputDStream.scala, scala/src/main/org/apache/spark/streaming/api/kafka/KafkaUtilsCSharpHelper.scala, scala/src/test/scala/org/apache/spark/streaming/api/csharp/RddPreComputeProcessorSuite.scala
Add ParallelKafkaDataFetcherDStream to fetch data from Kafka in parallel
=> support parallelly pre-fetch data for DynamicPartitionKafkaInputDStream

README.md, csharp/Samples/Microsoft.Spark.CSharp/App.config, examples/Batch/WordCount/App.config, examples/Batch/WordCountFSharp/App.config, examples/Batch/pi/App.config, examples/Sql/CassandraDataFrame/App.config, examples/Sql/HiveDataFrame/App.config, examples/Sql/JdbcDataFrame/App.config, examples/Sql/SparkXml/App.config, examples/Streaming/EventHub/App.config, examples/Streaming/Kafka/App.config, notes/linux-csharpworker-prefix-script.md, notes/linux-instructions.md, notes/linux-prefix-script.md, notes/running-mobius-app.md
Updated documentation and config files used in examples
=> updates to documentation for Mobius in Linux

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs, notes/linux-instructions.md, scala/src/main/org/apache/spark/deploy/csharp/CSharpRunner.scala, scala/src/test/scala/org/apache/spark/deploy/csharp/CSharpRunnerSuite.scala
validated fix for #467 using HDInsight cluster
Added unit test for the scala code change
Existing unit tests for ConfigurationService.cs cover the changes
=> fixes to run Mobius in Linux

csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IStreamingContextProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/CSharpInputDStreamUtils.cs, csharp/AdapterTest/DStreamTest.cs, csharp/AdapterTest/Mocks/MockStreamingContextProxy.cs, csharp/Samples/Microsoft.Spark.CSharp/DStreamSamples.cs, scala/src/main/org/apache/spark/streaming/api/csharp/CSharpDStream.scala, scala/src/test/scala/org/apache/spark/streaming/api/csharp/CSharpDStreamSuite.scala
Add CSharpInputDStream to enable control of data injection by C# code
=> Add CSharpInputDStream to enable control of data injection by C# code

csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/JvmBridgeUtils.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IDStreamProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/ISparkCLRProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IStreamingContextProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/DStreamIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/SparkCLRIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/DStream.cs, csharp/Adapter/Microsoft.Spark.CSharp/Streaming/StreamingContext.cs, csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML, csharp/Adapter/documentation/Mobius_API_Documentation.md, csharp/AdapterTest/DStreamTest.cs, csharp/AdapterTest/EventHubsUtilsTest.cs, csharp/AdapterTest/Mocks/MockDStreamProxy.cs, csharp/AdapterTest/Mocks/MockSparkCLRProxy.cs, csharp/AdapterTest/Mocks/MockStreamingContextProxy.cs, csharp/AdapterTest/StreamingContextTest.cs, csharp/AdapterTest/TestWithMoqDemo.cs, csharp/Samples/Microsoft.Spark.CSharp/DStreamSamples.cs, csharp/Samples/Microsoft.Spark.CSharp/DStreamStateSample.cs
In branch-1.6, time unit is millisecond. To avoid breaking change, change the time unit of back to millisecond in master branch to align with branch-1.6.
=> Change time unit of streaming back to millisecond

scala/src/main/org/apache/spark/streaming/api/csharp/CSharpDStream.scala, scala/src/test/scala/org/apache/spark/streaming/api/csharp/CSharpDStreamSuite.scala
@tawan0109 did a comprehensive investigation on hanging SparkSML application after running for a couple of hours and discovered that driver program didn't exit when parallel job threw exception in a different thread which failed to enqueue the rdd for which driver was waiting forever.
add try finally block to always enqueuer, if parallel job failed to materialize the rdd, let main thread retry it as usual.
=> add try finally block to parallel job since driver does not exit if the job fails

csharp/Worker/Microsoft.Spark.CSharp/Worker.cs
it was changed to low level enumerator API to add some perf metrics which actually can be done in normal enumerator as well.
=> refactoring to change low level enumerator back to normal

examples/Sql/HiveDataFrame/Program.cs, notes/running-mobius-app.md
Fix input json file path problem under Linux environment. Moreover, user could provide the input json file path manually.
=> Modify HiveDataFrame example

scala/src/main/org/apache/spark/api/csharp/CSharpBackend.scala, scala/src/main/org/apache/spark/api/csharp/CSharpBackendHandler.scala, scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala, scala/src/main/org/apache/spark/deploy/csharp/CSharpRunner.scala, scala/src/main/org/apache/spark/streaming/api/csharp/CSharpDStream.scala
Finish TODO "logError does not work now" and "TODO: change println to log"
=> Use logInfo and logError method instead of println

csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/WeakObjectManager.cs
Leaving the code intact but commented out in case Mobius project devs want to enable it back while investigating any issue
=> disabling log messages that are not useful to Mobius app developers

csharp/Adapter/Microsoft.Spark.CSharp/Sql/SparkSession.cs, csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML
=> Make SparkContext available through SparkSession

appveyor.yml
Remove api key per security policy
=> Remove api key per security policy
