microsoft/Mobius

csharp/AdapterTest/DataFrameTest.cs
csharp/AdapterTest/RDDTest.cs
csharp/AdapterTest/SqlContextTest.cs

- Several test cases have same names but in different namespaces, but FQN does not show in many test runners like Visual Studio.
- Added `Rdd` or `SqlContext` or `DataFrame` into the test name as appropriate, for disambiguation.

Rename dup test names by adding Rdd/SqlContext/DataFrame for clarity.

---

csharp/SparkCLR.nuspec

Separate copy of SparkCLR.nuspec file
- Split out SparkCLR.nuspec from PR #6 commit 6e87a820e60f6337bd1adfe08c7e3dc90988644b
Some outstanding questions still to be worked out wrt the correct contents of the .nuspec file:
@skaarthik  wrote:
``` xml
<requireLicenseAcceptance>false</requireLicenseAcceptance>
```
> I will get back to this PR after learning more about this tag in the context of this project

SparkCLR.nuspec file

---

csharp/Worker/Microsoft.Spark.CSharp/Worker.cs

UnixTimeEpoch
- Calculate base time stamp for UnixTimeEpoch once, rather than each time it is used.

UnixTimeEpoch

---

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Core/DoubleRDDFunctions.cs
csharp/Adapter/Microsoft.Spark.CSharp/Core/PairRDDFunctions.cs
csharp/Adapter/Microsoft.Spark.CSharp/Core/RDD.cs
csharp/Adapter/Microsoft.Spark.CSharp/Core/SparkContext.cs
csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrame.cs
csharp/Adapter/Microsoft.Spark.CSharp/Sql/Functions.cs
csharp/Adapter/Microsoft.Spark.CSharp/Streaming/StreamingContext.cs

Fix some minor issues in code-docs and messages.
- Fix various minor issues with XML code-docs.
- Mostly required replacing < with &lt; for valid XML.
- Fix minor typo in comment.
- Fix wrong parameters being passed into string.Format

Fix minor issues in code-docs

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/RDD.cs
csharp/Samples/Microsoft.Spark.CSharp/MiscSamples.cs

Minor code tweaks
- The `buffer` variable in `RDD.Collect` can never be null, so that check can be removed from the loop.
- Make `PiSample` more discoverable, by making it have same `internal` visibility as other Samples project example code.

Minor code tweaks 1105

---

csharp/AdapterTest/Mocks/MockDataFrameProxy.cs

Add the missing methods in MockDataFrameProxy
- Fixes build break from PR #22
https://github.com/Microsoft/SparkCLR/pull/22

Missing methods in MockDataFrameProxy

---

csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IDataFrameProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/IStructProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/DataFrameIpcProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StructIpcProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrame.cs
csharp/Adapter/Microsoft.Spark.CSharp/Sql/Row.cs
csharp/Adapter/Microsoft.Spark.CSharp/Sql/Struct.cs
csharp/AdapterTest/Mocks/MockDataFrameProxy.cs
csharp/Samples/Microsoft.Spark.CSharp/DataFrameSamples.cs

Work flow:
Java Side:
1. Call javaToPython() to convert DataFrame to javaRDD[Array[Byte]]
2. Get RDD [Array[Byte]] from javaRDD[Array[Byte]]
3. Call PythonRDD.collectAndServe to send the RDD via socket
C# side:
1. Read from socket and construct a list of Row.
2. Convert the list to IEnumerable and return
Code change:
1. Add a file Row.cs, defining the class Row and RowImpl.
2. Add RPC call to get datatype info from Java side in json format.
Here is an example:
{"type":"struct","fields":[{"name":"address","type":{"type":"struct","fields":[{"name":"city","type":"string","nullable":true,"metadata":{}},{"name":"state","type":"string","nullable":true,"metadata":{}}]},"nullable":true,"metadata":{}},{"name":"age","type":"long","nullable":true,"metadata":{}},{"name":"id","type":"string","nullable" …

Add collect() API for DataFrame

---

.gitignore
Build.cmd
RunSamples.cmd

This is my attempt to create a top-level meta-build script, which runs the scala and csharp builds to create those sub-component, and then assembles all the runtime binaries and samples into a `run` directory with the structure defined in the [README](https://github.com/Microsoft/SparkCLR/blob/master/README.md)
In addition, any extra `*.jar` libraries placed into the top level `lib` directory will be copies into the `run\lib` directory too. This is great for handling the extra csv libraries required for the DataFrame TextFile API.
Finally, a `RunSamples.cmd` script provides a simplified way to run through all the SparkCLR Sample using the staged `run` directory tree created above.
Please take a look and see if I this creates the expected runtime artifacts.
For reference, below is the …

Meta Build Script and Run Samples

---

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Configuration/IConfigurationService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/JvmBridge.cs
csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/SparkCLRSocket.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/SparkContextIpcProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/SqlContextIpcProxy.cs
csharp/AdapterTest/Mocks/MockConfigurationService.cs

Minor improvements to handling some error conditions and first-use confusion points.
Improved error reporting of missing `CSharpWorkerPath` App.config value.
- Throw `ConfigurationErrorsException` with more specific message about missing `CSharpWorkerPath` value in `App.config`.
~~For Local configuration, use the file name part of the `CSharpWorkerPath` value, if specified,
otherwise use the default value `CSharpWorker.exe` from base class.~~
Guard against `NullReferenceException` in `Dispose()`.
~~Add `GetJavaPort` method to prompt user for port number and read console.~~

Minor improvements to handling some error conditions.

---

scala/src/main/org/apache/spark/launcher/SparkCLRSubmitArguments.scala

Remove '-exe <driver.exe>'  from usage line.

Fix minor error in the printed usage of sparkclr-submit

---

RunSamples.cmd
scala/src/main/org/apache/spark/launcher/SparkCLRSubmitArguments.scala

1. Extra arguments can be passed to RunSamples.cmd.
2. Now single sample can be launched by 'RunSamples.cmd sparkclr.samples.torun <SampleName>'.
3. Options that is supported by SparkCLRSamples.exe can also be supported by RunSamples.cmd automatically.

RunSamples.cmd could receive arguments

---

README.md

1. Add env variable `SPARK_HOME`, explicitly point out which version of Spark currently SparkCLR supports.
2. Add env variable `HADOOP_HOME`. As SPARK-2356 is still unresolved, `java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries` will happen if user runs samples on local Windows machine. There are probably many workarounds for this issue, here just choose a simple one for user to follow.
3. Remove unused env variable `SCALA_HOME`

Update README.md, add two extra enviroment variables in `Running Samples` section

---

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Configuration/IConfigurationService.cs

* Fixed `CSharpWorkerExePath` does not exist in standalone mode issue, now the returned value for `CSharpWorkerExePath` is changed back to `CSharpWorker.exe` for standalone mode.
* Make the `procFileName` (CSharpWorker.exe) as the default value for `CSharpWorkerExePath`, remove class SparkCLRYarnConfiguration.
* Remove unused method `GetDriverFiles()` from interface `IConfigurationService` and classes implemented `IConfigurationService`.
* When call method `GetCSharpWorkerExePath()` in class `SparkCLRDebugConfiguration`,  setting item `CSharpWorkerPath` in App.config will be returned if it is set, this is aligned with `Debugging Tips` section in `README.md`.

Fix `CSharpWorkerExePath` does not exist issue in standalone mode & code clean up

---

csharp/Samples/Microsoft.Spark.CSharp/Samples.csproj

Microsoft.VisualStudio.QualityTools.UnitTestFramework is not part of .Net Framework (just part of VS IDE); by enabling "Copy Local" to true in the reference, the DLL will be included as part of final build, which avoids the exception of missing UnitTestFramework.dll when running on servers without VS IDE installed.
Running "sparkclr.samples.torun PiSample" in the cluster without VS IDE installed repro's this issue.

Microsoft.VisualStudio.QualityTools.UnitTestFramework not found at runtime

---

Build.cmd

* When error happens during `scala` or `csharp` components building, build.cmd does not stop and continue to do the left steps.
* Check `ERRORLEVEL` and stop building if the `ERRORLEVEL` is not equal `0`

Build.cmd does not stop when build errors happen

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/Accumulator.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/DStreamIpcProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/SparkCLRIpcProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Streaming/DStream.cs
csharp/Adapter/Microsoft.Spark.CSharp/Streaming/PairDStreamFunctions.cs
csharp/Adapter/Microsoft.Spark.CSharp/Streaming/TransformedDStream.cs
csharp/Samples/Microsoft.Spark.CSharp/DStreamSamples.cs

accumulator id not get passed causing all accumulators having id '0', uses underlying java / scala dstream jvm reference in a consistent way

fix accumulator id and refactor dstream jvm reference

---

scala/src/main/org/apache/spark/deploy/csharp/CSharpRunner.scala

* `getParentFile()` returns `null` if given pathname does not name a parent, call `getAbsoluteFile()` before `getParentFile()` to fix this issue.
* Refine log to include the zip file name as well as driver working directory.

Fix NPE in CSharpRunner

---

Build.cmd
RunSamples.cmd
csharp/Samples/Microsoft.Spark.CSharp/App.config
csharp/Samples/Microsoft.Spark.CSharp/Program.cs
csharp/Worker/Microsoft.Spark.CSharp/App.config
downloadtools.ps1
scala/src/main/org/apache/spark/deploy/csharp/CSharpRunner.scala
scripts/spark.conf/executor.log.properties
scripts/spark.conf/log4j.properties
scripts/spark.conf/spark-1.4.1-log4j.properties.template
scripts/sparkclr-submit.cmd
scripts/zipdir.ps1

minor changes across a few files.
Runsamples.cmd accepts "--verbose" flag. By default, FileAppender replaces ConsoleAppender in Spark log4j.properties, SparkCLR App.Config; FileAppender produce logs at %TEMP%\SparkCLRLogs. When "--verbose" flag is added, ConsoleAppenders are enabled, in addition to FileAppender.
Try PiSample to see the difference - 
(1) runsamples --torun pi* 
(2) runsamples --verbose --torun pi*

clear the clutter in console output when running samples

---

RunSamples.cmd

* When executed RunSample.cmd on WIndows 10 (Version 10.0.10240 by `ver` command), following error happened:
<pre>
D:\SparkWorkspace\SparkCLR>RunSamples.cmd --validate
SPARK_VERSION=1.4.1
HADOOP_VERSION=2.6
Set-ExecutionPolicy : Access to the registry key
'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' is denied. To change the execution
policy for the default (LocalMachine) scope, start Windows PowerShell with the "Run as administrator" option. To
change the execution policy for the current user, run "Set-ExecutionPolicy -Scope CurrentUser".
At line:1 char:1
> + Set-ExecutionPolicy Unrestricted
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], UnauthorizedAccessException
>    + …

Fix PowerShell System.UnauthorizedAccessException issue when execute RunSamples.cmd

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/RDD.cs

In Microsoft.Spark.CSharp.Core.RDD, method Collect creates a socket without explicitly specifying the AddressFamily, which by default is InterNetworkv6 (ip v6). This also cause "invalid argument" exceptions on Linux when calling collect on RDD.
This is also inconsistent with other places in SpakCLR, e.g., SparkCLRSocket or JvmBridge, where sockets always explicitly use AddressFamily.InterNetwork (ip v4).

[Issue #111]Fix Inconsistent addressing schemes used by sockets in SparkCLR

---

.gitignore
appveyor.yml
precheck.cmd

This change added complete sample run, with --validate flag, after unit test. It increases build-time at AppVeyor from 5 minute to 13 minutes and 30 seconds. We will observe closely whether the increase in build-time negatively impact the productivity - if it does, we will run selected sample test.

add runsamples; proceed with build even not dev command prompt for VS

---

scala/pom.xml
scala/scalastyle-config.xml

* Enable scala style check in `pom.xml`
* Use same `scalastyle-config.xml` with spark.
* Set `failOnViolation` to `false` for `scalastyle-maven-plugin` for now.
* Use `mvn verify` to check scala style, results can be found in `target/scalastyle-output.xml`
* If this PR accepted, will make changes to scala files to resolve detected warnings.

Enable scala style check in pom.xml

---

csharp/Adapter/Microsoft.Spark.CSharp/Sql/DataFrame.cs
csharp/AdapterTest/DataFrameTest.cs
csharp/Samples/Microsoft.Spark.CSharp/DataFrameSamples.cs
csharp/Worker/Microsoft.Spark.CSharp/Worker.cs

* When run samples `DFForeachPartitionSample` and `DFForeachSample`, exception `Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference` happened in `Worker.cs`
* Add null check in `Worker.cs` to prevent this exception
* Add unit tests

Fix RuntimeBinderException in Worker.cs when run samples DFForeachPartitionSample and DFForeachSample

---

csharp/Samples/Microsoft.Spark.CSharp/Program.cs
csharp/Samples/Microsoft.Spark.CSharp/SamplesRunner.cs

This fix enables SamplesRunner to propagate out test status, which will fix the after_test task "RunSamples.cmd --validate" in AppVeyor. This PR fixes #134

SamplesRunner propgates test status to CI

---

appveyor.yml
csharp/AdapterTest/AdapterTest.csproj
csharp/AdapterTest/ComparableRDDTest.cs
csharp/AdapterTest/DataFrameTest.cs
csharp/AdapterTest/DoubleRDDTest.cs
csharp/AdapterTest/PairRDDTest.cs
csharp/AdapterTest/RDDTest.cs
csharp/AdapterTest/SparkCLRTestEnvironment.cs
csharp/AdapterTest/packages.config
csharp/Samples/Microsoft.Spark.CSharp/Samples.csproj
csharp/Samples/Microsoft.Spark.CSharp/packages.config

Update unit test to use NUnit3, as AppVeyor is upgraded to use NUnit3.
Explicitly set assemblies to test, as AppVeyor test auto-detection will detect SparkCLRSamples.exe but fail to find any testfixtures in it.

Update to nunit3 as appveyor is upgraded

---

scala/src/main/org/apache/spark/launcher/SparkCLRSubmitArguments.scala
scala/src/test/scala/org/apache/spark/launcher/SparkCLRSubmitArgumentsSuite.scala

Set executable name as app name when app.name is not explicitly set

---

linux-instructions.md
scala/src/main/org/apache/spark/launcher/SparkCLRSubmitArguments.scala
scala/src/test/scala/org/apache/spark/launcher/SparkCLRSubmitArgumentsSuite.scala
scripts/sparkclr-submit.cmd
scripts/sparkclr-submit.sh
windows-instructions.md

* Add new option `--remote-sparkclr-jar` to `sparkclr-submit.cmd`,  this new option is only required for standalone cluster mode.
* When option `--deploy-mode` is specified with `cluster`, option `--remote-sparkclr-jar` is required and needs to be specified with a valid file path of spark-clr*.jar on HDFS.
* Make changes to Windows-instructions.md, Linux-instructions.md and sparkclr-submit.cmd to reflect this change.
* Unit tests

Enable '--remote-sparkclr-jar' option for standalone cluster mode

---

.gitignore

- Ignore compiler / IDE temp directories at any depth in the directory tree, rather than individually.
```
bin
obj
packages
target
.idea
```

MINOR: Clean up and simplify .gitignore file.

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/Accumulator.cs
csharp/Adapter/Microsoft.Spark.CSharp/Core/RDDCollector.cs
csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/JvmBridge.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/SparkContextIpcProxy.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs
csharp/AdapterTest/Mocks/MockSparkContextProxy.cs
csharp/AdapterTest/StreamingContextTest.cs
csharp/AdapterTest/TestWithMoqDemo.cs
csharp/Worker/Microsoft.Spark.CSharp/Worker.cs
csharp/WorkerTest/WorkerTest.cs

- Use the pre-defined `IPAddress.Loopback` value that .NET provides, rather than magic constants.

MINOR: IPAddress.Loopback

---

csharp/Samples/Microsoft.Spark.CSharp/MiscSamples.cs
csharp/WorkerTest/WorkerTest.cs

- Use Path.Combine for better cross-platform support for building the worker exe path, rather than hard coding the Windows specific backslash path separator.
- Assembly.Location can return null in some cases (particularly dynamic loading) so default to current directory "." in that case.
- Output the worker exe path being used, for easier debugging of tests not working.
- Use object initializer syntax for creating Process.StartInfo -- more compact and readable code.

Use Path.Combine to building worker exe path.

---

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/SparkContextIpcProxy.cs
scala/src/main/org/apache/spark/api/csharp/CSharpBackendHandler.scala
scala/src/test/scala/org/apache/spark/api/csharp/CSharpBackendHandlerSuite.scala

When run dataframe sample `DFNaFillSample` on Linux, below exception was thown:
```
argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.apache.spark.api.csharp.CSharpBackendHandler.handleMethodCall(CSharpBackendHandler.scala:147)
at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:90)
at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:25)
at …
```

Fix wrong method invoked issue in CSharpBackendHandler

---

csharp/Adapter/Microsoft.Spark.CSharp/Sql/Types.cs

As interface `IStructTypeProxy` has already defined method `ToJson()`, so here no need to cast `structTypeProxy ` to class `StructTypeIpcProxy`. This change will make class `StructType` easy to test.

Minor change to class `StructType` to make it easy to test

---

examples/Examples.sln
examples/pi/App.config
examples/pi/Pi.csproj
examples/pi/Program.cs
examples/pi/Properties/AssemblyInfo.cs
examples/pi/packages.config

A developer should refer SparkCLR nuget package, when writing a SparkCLR job. This is the first attempt in offering a PiExample. Borrowed all code from existing SparkCLR sample run.
Tested by including SparkCLR package from local folder.
Next: need to provide a readme to cover (1) how to build; (2) how to submit the job.

convert PiSample to PiExample consuming SparkCLR nuget package

---

scala/scalastyle-config.xml
scala/src/main/org/apache/spark/api/csharp/CSharpBackend.scala
scala/src/main/org/apache/spark/api/csharp/CSharpBackendHandler.scala
scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala
scala/src/main/org/apache/spark/api/csharp/SerDe.scala
scala/src/main/org/apache/spark/deploy/csharp/CSharpRunner.scala
scala/src/main/org/apache/spark/launcher/SparkCLRSubmitArguments.scala
scala/src/main/org/apache/spark/sql/api/csharp/SQLUtils.scala
scala/src/main/org/apache/spark/streaming/api/csharp/CSharpDStream.scala
scala/src/main/org/apache/spark/util/csharp/Utils.scala
scala/src/test/scala/org/apache/spark/api/csharp/CSharpBackendHandlerSuite.scala
scala/src/test/scala/org/apache/spark/csharp/SparkCLRFunSuite.scala
scala/src/test/scala/org/apache/spark/launcher/SparkCLRSubmitArgumentsSuite.scala
scala/src/test/scala/org/apache/spark/util/csharp/UtilsSuite.scala

* Change copyright header format of `.scala` files from "#...#" to "/*...*/" to align with Spark.
* Remove commented codes.
* Wrap lines which the lengths exceed `maxLineLength` defined in `scalastyle-config.xml`

Fix scalastyle check warnings

---

README.md

Example looks cleaner if we don't use the `(string[], StringSplitOptions)` overload for a single character split :bowtie:

Simplify the `Split` expression

---

csharp/Samples/Microsoft.Spark.CSharp/RDDSamples.cs

Applies change from #222 to the samples

Modify samples to use simpler `String.Split` overload where possible

---

csharp/Samples/Microsoft.Spark.CSharp/SparkContextSamples.cs

In sample `SparkContextSamples.SparkContextBroadcastSample()`, broadcast variable `b` is used in following way:
```c#
SparkContext.Parallelize(new[] { 0, 0 }, 1).FlatMap(new BroadcastHelper<int>(b.Value).Execute).Collect();
```
However, the right way to use Broadcast variable `b` should be like this:
```c#
SparkContext.Parallelize(new[] { 0, 0 }, 1).FlatMap(new BroadcastHelper<int>(b).Execute).Collect(); 
```

Use spark broadcast variables in the right way in SparkContextBroadcastSample

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/Broadcast.cs
csharp/Adapter/Microsoft.Spark.CSharp/Core/SparkContext.cs
csharp/AdapterTest/AdapterTest.csproj
csharp/AdapterTest/BroadcastTest.cs
csharp/AdapterTest/SparkContextTest.cs

* Fix null check failure issue when `T` is a primitive type in `Broadcast.cs`
* Remove unused method `internal CheckpointFile<T>(string filePath, SerializedMode serializedMode)` in `SparkContext.cs`
*  Add unit tests to improve test coverage of `Broadcast` and `SparkContext`

Fix null check issue in Broadcast & Add unit tests

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/RDD.cs
csharp/AdapterTest/AdapterTest.csproj
csharp/AdapterTest/Mocks/MockRddProxy.cs
csharp/AdapterTest/PairRDDTest.cs
csharp/AdapterTest/RDDTest.cs
csharp/AdapterTest/StatusTrackerTest.cs

* Remove unused method `internal int DefaultReducePartitions` in `RDD`
* Improve test coverage of `PairRDDFunctions`
* Improve test coverage of `RDD`
* Improve test coverage of `StatusTracker`

Remove unused methods in RDD & Improve test coverage in 'Core' namespace.

---

csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/JvmObjectReference.cs
csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/SerDe.cs
csharp/AdapterTest/AdapterTest.csproj
csharp/AdapterTest/PayloadHelperTest.cs
csharp/AdapterTest/SerDeTest.cs

* Improve test coverage of `SerDe.cs`
* Improve test coverage of `PayloadHelper.cs`
* Remove unused method `SerDe.Convert(int value)`, `SerDe.Convert(long value)` and `SerDe.Convert(double value)`

Improve test coverage in 'utils' & remove unused methods in SerDe.cs

---

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs
csharp/AdapterTest/AccumulatorTest.cs

1. Let the C# process exit if it processes CallBackRequest fail
2. Refactor the accumulator test, add test cases

Let the C# process exit if it processes CallBackRequest fail

---

build/localmode/RunSamples.cmd
build/localmode/precheck.cmd

This tweak to `RunSamples.cmd` script makes it easier to detect any problems in the build environment, because build agent [eg VSO] will detect non-zero exit code which was previously being masked by extra commands at end of script.
- `RunSamples.cmd` should signal runtime failure if non-zero RC from underlying call to `sparkclr-submit.cmd` script. [The final `popd` was previously masking this value.]
- Fix non-standard usage of quotes between RunSamples.cmd and PreCheck.cmd scripts.
- Print directory location info for strategic pushd's
Should have no affect on the core team's Appveyor build, but my private VSO build was not detecting / marking build failures when it should have been due to some test config issues.

RunSamples.cmd should signal failure if non-zero RC from sparkclr-submit script

---

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/DataFrameWriterIpcProxy.cs

For `DataFrameWriter.jdbc(url: String, table: String, connectionProperties: Properties)`, the third parameter is required to be a `java.util.Properties` type object. Here explicitly create a `java.util.Properties` object in jvm with the given c# `Dictionary` object `properties`.

Fix the issue in convering properties with jdbc implementation

---

examples/pi/Program.cs

Checkpoint directory needs to be a HDFS path when the deploy mode is `yarn-cluster`. Remove `SparkContext.SetCheckpointDir(Path.GetTempPath());` to make `Pi` example run well in `yarn-cluster` mode.

Fix Pi example can't run in yarn-cluster mode issue

---

.gitignore
appveyor.yml
build/Build.cmd
build/build.sh
build/localmode/RunSamples.cmd
build/localmode/downloadtools.ps1
build/localmode/precheck.cmd
csharp/Build.cmd

I have found these changes were required to get SparkCLR building again on my VSO instance, mostly due to problems with mvn settings. 
PR #257 commit 7159d9191f231e6f9e4b527322152d15fa1e2594 helped unmask the VSO build problems, which had been happening for a while.
The main part of the change is this:
- If mvn not already installed, then set M2 env variables from download 
d4310ce4bd243a77872c989b14ba195720aba4d1
This change set also contains a tweak to run mvn in --quiet more on the build servers, because the massive amount of download progress messages in the build log were also causing any build issues to be hard to spot.
- Run Maven in `--quiet` mode to avoid all the download progress messages in the build server logs.
c3eaa3afe31371a7d1fc5144f1e5d184c4116368
The other parts of this …

M2 build settings and mvn --quiet

---

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/SparkContextIpcProxy.cs

The prototype for all the Hadoop API mehtods is expecting a `java.util.HashMap` as the `conf` argument, however now a `java.util.Hashtable` is passed and the invocation fails with:
```java
cannot find matching method class org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD. Candidates are:
newAPIHadoopRDD(class org.apache.spark.api.java.JavaSparkContext,class java.lang.String,class java.lang.String,class java.lang.String,class java.lang.String,class java.lang.String,class java.util.HashMap,int)
newAPIHadoopRDD on object of type NullObject failed
No matched method found for class org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD
java.lang.Exception: No matched method found for class org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD
at …
```

fix conf argument type in the proxy to Hadoop API methods

---

csharp/Samples/Microsoft.Spark.CSharp/RDDSamples.cs

In current `RDDCheckpointSample`, `Console.WriteLine(rdd.IsCheckpointed)` always print out `false`.
Call `Count()` action of the RDD to make sure `doCheckpoint` method invoked and `rdd.IsCheckpointed` returns true.

Improve RDDCheckpointSample and add validations

---

csharp/Samples/Microsoft.Spark.CSharp/CommandlineArgumentProcessor.cs
csharp/Samples/Microsoft.Spark.CSharp/Configuration.cs
csharp/Samples/Microsoft.Spark.CSharp/Program.cs

* Currently in SparkCLR samples checkpoint directory is set to a local temp path.
* Samples breaks when it is running in yarn mode.
* Add new parameter `--checkpointdir` to explicitly specify a checkpoint directory(HDFS path for yarn mode).
* To be backward compatible, checkpoint directory is set to a local temp path when `--checkpointdir` is not specified.

Add '--checkpointdir' to explicity specify checkpoint directory when run samples

---

scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaInputDStream.scala

* Currently the thread names for all`refreshOffsetsScheduler` instances are same, which can't be distinguished in logs.
* Set the name to `refresh-offsets-%d` won't solve the problem.
* For each thread name, append a random uuid (only use first 8 chars).

Make the name of 'referesh-offsets' thread unique for different DynamicPartitionKafkaInputDStream instances

---

csharp/Worker/Microsoft.Spark.CSharp/MultiThreadWorker.cs
csharp/Worker/Microsoft.Spark.CSharp/TaskRunner.cs
csharp/Worker/Microsoft.Spark.CSharp/Worker.cs
csharp/WorkerTest/WorkerTest.cs

1. In MultiThreadWorker mode, does not let the whole worker process exit when some TaskRunner fails.
2. Minor change to improve log info in worker

In MultiThreadWorker mode, does not let the whole worker process exit when some TaskRunner fails

---

csharp/WorkerTest/WorkerTest.cs

The test of assertMessage should be postponed after worker exit.

Fix the UT - TestBroadcastVariablesInWorker

---

csharp/Adapter/Microsoft.Spark.CSharp/Interop/SparkCLREnvironment.cs
csharp/AdapterTest/RowTest.cs
csharp/AdapterTest/SerDeTest.cs
csharp/AdapterTest/SqlContextTest.cs
csharp/SparkCLR.sln
csharp/Tests.Common/Picklers.cs
csharp/Tests.Common/Properties/AssemblyInfo.cs
csharp/Tests.Common/RowHelper.cs
csharp/Tests.Common/Tests.Common.csproj
csharp/WorkerTest/WorkerTest.cs
csharp/WorkerTest/WorkerTest.csproj

1. Add unit tests to improve code coverage for "SQL" namespace
2. Create a new common library that shared by AdapterTest and WorkerTest. And move common code to the new library.

Improve unit test coverage in SQL namespace

---

.gitignore
build/Build.cmd

The release zip file includes source files under "examples" folder. the fix is to include examples binaries in release zip file.
Refer to #289

Fix Build.cmd to include examples binaries in release zip file

---

examples/Sql/JdbcDataFrame/JdbcDataFrame.csproj
examples/Sql/SparkXml/SparkXml.csproj
examples/Streaming/EventHub/EventHub.csproj

Examples.sln build failed on branch-1.6 due to the wrong reference of Mobius preview in csproj files

Fix build failure of Examples.sln for branch-1.6

---

build/Build.cmd

Currently, the build process cannot be stopped if Examples solution has compiling failure. The fix is to stop building process if Examples failed.

Fix Build.cmd to stop building when Examples compiling failed

---

scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala
scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaRDD.scala
scala/src/test/scala/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaRDDSuite.scala

Spark config parsing ignores configs that do not have "spark." prefix

renamed mobius config names

---

scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaInputDStream.scala

In current implementation, `refreshOffsetsScheduler` is started to schedule `setOffsetsRangeForNextBatch` task in `instantiateAndStartRefreshOffsetsScheduler`.
However, in `start()` method, `refreshOffsetsScheduler` is not null for a refresh start(not restoring from checkpoint), so `refreshOffsetsScheduler` has no chance to start scheduling by calling `scheduleAtFixedRate`

Fixing refreshOffsetsScheduler do not start scheduling tasks issue

---

csharp/build.sh
examples/build.sh

Empty strings should be checked with `[ -z $foo ]` instead of `[ $foo = "" ]` 🎉

Fixing unary operator error in Linux build scripts

---

build/localmode/downloadtools.ps1

Update download path of winutils.exe to fix running localmode example problem (such as: permission of /tmp/hive)

Update download path of winutils.exe to fix running localmode example problem

---

notes/linux-instructions.md

F# documentation to allow F# work count example to compile under build step.  Also version of Maven that is standard in the Debian repository, therefore which is pulled by apt for Debian, Ubuntu, Mint, etc. is 3.0.5 not 3.3.x.  I had no problems running any of the scripts with that version of Maven.

Add F# documentation and Maven version data

---

scala/src/main/org/apache/spark/launcher/SparkCLRSubmitArguments.scala
scala/src/test/scala/org/apache/spark/launcher/SparkCLRSubmitArgumentsSuite.scala

Fix error passing arguments of sparkclr-submit to spark-submit when arguments contain special characters.
for example : an arg is a connection string as following :
"jdbc:mysql://localhost:3306/lzdb?user=guest&password=abc123"
it contains "&" , cannot pass it from sparkclr-submit.cmd to spark-submit.cmd, even if you quote it like above. 
Error happens in script : https://github.com/Microsoft/Mobius/blob/master/scripts/sparkclr-submit.cmd#L62
The quote (if you added) will disappear in file  LAUNCHER_OUTPUT.

Fix error passing arguments of sparkclr-submit to spark-submit when arguments contain special characters.

---

build/Build.cmd

* `copy` operation overwrites `%ERRORLEVEL%` returned by `mvn.cmd build`, which caused build script failed to check whether scala build succeed or not.
* This PR tries to saves `%ERRORLEVEL%` to a variable `MVN_ERRORLEVEL` before do any other operations, and use this variable to check mvn build status.

Fixing issue that build did not stop when mvn build failed

---

csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs
scala/src/main/org/apache/spark/streaming/api/csharp/CSharpDStream.scala
scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaInputDStream.scala
scala/src/test/scala/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaInputDStreamSuite.scala

1. fix DynamicPartitionKafkaInputDStream checkpoint by fixing restore method and starting streaming callback server ealier during restore time
2. add C# func support in DynamicPartitionKafkaInputDStream by inheriting from InputDStream directly

fix DynamicPartitionKafkaInputDStream checkpint and add C# func support

---

csharp/Build.cmd
csharp/Clean.cmd
examples/Build.cmd
examples/Clean.cmd

Currently, we are using the msbuild with v4.0 to compile .NET code. this change is to consume v12.0 one.

Fix build scripts to comsume msbuild v12.0

---

csharp/Worker/Microsoft.Spark.CSharp/App.config

* Usually it's not necessary to enable two log appenders at the same time. For `LogFileAppender`, the output location is under `%TEMP%` directory (on drive `C:\` by default). We should let user to make the call whether to write logs to `%TEMP%` directory.
* Comment out `LogFileAppender` in CSharpWorker `app.config`, only `ConsoleAppender` is enabled by default

Disabled LogFileAppender for CSharpWorker

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/PairRDDFunctions.cs
csharp/Adapter/Microsoft.Spark.CSharp/Streaming/PairDStreamFunctions.cs
scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaRDD.scala
scala/src/test/scala/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaRDDSuite.scala

1. add "cluster.id" in kafkaParams when calling KafkaUtils.CreateDirectStreamWithRepartition to unique identify a topic.
2. refactor UpdateStateByKey API to complete pipelined RDD before transforming to CSharpStateDStream so that no extra CSharpRDDs in UpdateStateByKey and its parallel job covers all pipelined operations before shuffling.

add kafka cluster id and refactor UpdateStateByKey API

---

csharp/Adapter/Microsoft.Spark.CSharp/Streaming/PairDStreamFunctions.cs
csharp/AdapterTest/DStreamTest.cs
csharp/AdapterTest/Mocks/MockRddProxy.cs
csharp/AdapterTest/Mocks/MockStreamingContextProxy.cs
csharp/Samples/Microsoft.Spark.CSharp/DStreamSamples.cs

* By default Spark `updateStateByKey` supports parameter `initialRDD` [[link](https://github.com/apache/spark/blob/master/streaming/src/main/scala/org/apache/spark/streaming/dstream/PairDStreamFunctions.scala#L475)], which represents the initial state value of each key.
* Add this parameter to Mobius `UpdateStateByKey()`

Operator updateStateByKey supports initial state RDD

---

csharp/Adapter/Microsoft.Spark.CSharp/Streaming/PairDStreamFunctions.cs
csharp/Samples/Microsoft.Spark.CSharp/DStreamSamples.cs

in addition to tqin's fix:
1. a typo
2. remove prevFunc since not applicable
added:
1. sample validation
2. explicit numPartitions parameters when calling ReduceByKey

add validation to tqin's for ReduceByKeyAndWindow

---

csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/WeakObjectManager.cs
csharp/AdapterTest/WeakObjectManagerTest.cs

When check and release unused JVMObjectTracker objects, change the speed adaptively according to current objects count.

When check and release unused JVMObjectTracker objects, change the speed adaptively according to current objects count.

---

.travis.yml
appveyor.yml
build/localmode/downloadtools.ps1

Version 3.3.3 is no longer available at http://www.us.apache.org/dist/maven/maven-3. Upgrading to the latest version.

updating maven version

---

build/localmode/downloadtools.ps1
scala/src/main/org/apache/spark/streaming/api/csharp/CSharpDStream.scala
scala/src/main/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaInputDStream.scala
scala/src/test/scala/org/apache/spark/streaming/api/csharp/CSharpDStreamSuite.scala
scala/src/test/scala/org/apache/spark/streaming/api/kafka/DynamicPartitionKafkaInputDStreamSuite.scala

For stateful operation `UpdateStateByKey`, as we know, checkpoint is necessary for RDD lineage truncation and failure recovery by saving state data to reliable storage. However, it’s very challenging to checkpoint large volume data with a reasonable time expense.
In the scenario that the input stream is from Kafka, and the state (data to be checkpointed) can be rebuild by replaying last *N* batches, there is an alternative to Spark checkpoint. This PR tries to provide this alternative solution by combining RDD local checkpoint with offset range checkpoint of `KafkaDynamicRepartitionInputDStream`.
Solution:
* Save Kafka read offset range data into a staging directory`{spark.checkpointDirectory}\kafka-checkpoint\offsets_<batch_time_in_millseconds>.staging` at the beginning of each batch.
* …

Rebuild state for DStream UpdateStateByKey operation by replaying batches instead of checkpoint 

---

csharp/Adapter/Microsoft.Spark.CSharp/Network/ByteBufChunk.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/ByteBufPool.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/RioSocketWrapper.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/SocketStream.cs
csharp/WorkerTest/MultiThreadWorkerTest.cs
csharp/WorkerTest/WorkerTest.cs

This is to fix bugs in RioSocketWrapper and SocketStream that cause vstest.console.exe with /enablecodecoverage failed.

Fix bugs in RioSocketWrapper and SocketStream that cause vstest failed

---

appveyor.yml
build/localmode/downloadtools.ps1

Using Dynamic Code Coverage Tools of Visual Studio to generate C++ code coverage reports in CodeCov.io.
Limitation:
Currently, CodeCov can supports the reports generated by Dynamic Code Coverage Tools of Visual Studio with only one module. CodeCov is working on the fix to support multiple modules in the reports. In the meanwhile, CodeCov is also working on to support the reports generated by vstest.consle.exe with /enablecodecoverage parameter.
Please see [https://github.com/codecov/support/issues/255] for more information.

Implement automatic code coverage reports for c++ code

---

README.md
notes/CONTRIBUTING.md
notes/linux-instructions.md
notes/mobius-shell.md
notes/windows-instructions.md

Currently, some markdown files conatin links which are broken due to wrong file locations.
Please refer to my changed files. 
Except those broken links, I add `./` prefix to links in markdown files to stay code style the same.
BTW, I also remove extra spaces in these markdown files.

fix broken links in markdown files

---

build/Build.cmd

This PR tries to fix the build error in AppVeyor.

Escaped special characters in build.cmd

---

csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj
csharp/Adapter/Microsoft.Spark.CSharp/Core/PriorityQueue.cs
csharp/Adapter/Microsoft.Spark.CSharp/Core/RDD.cs
csharp/AdapterTest/AdapterTest.csproj
csharp/AdapterTest/PriorityQueueTest.cs

Current implementation for RDD `TakeOrdered` and `Top` operations is based on in-memory sort, which can't handle the scenario that partition data is too large to fit into memory.
This PR tries to solve this problem by 
* Using a bounded priority queue to find out the top K elements for each partition, priority queue only holds K elements in memory and don't need to sort all data first
* Adding an extra `Reduce` operation to aggregate the result data from each partition.
* Implementing `Top` operation by `TakeOrdered` operation.

Improve the implementation of RDD TakeOrdered and Top operations

---

csharp/Adapter/Microsoft.Spark.CSharp/Adapter.csproj
csharp/Adapter/Microsoft.Spark.CSharp/Network/SocketStream.cs
csharp/AdapterTest/AdapterTest.csproj
csharp/AdapterTest/SocketWrapperTest.cs
csharp/Perf/Microsoft.Spark.CSharp/PerfBenchmark.csproj
csharp/Samples/Microsoft.Spark.CSharp/Samples.csproj
csharp/Worker/Microsoft.Spark.CSharp/Worker.csproj
csharp/WorkerTest/WorkerTest.csproj

1. Fix SocketStream.ReadByte() to release unreadable cache
2. Delete unnecessary copy of Riosock.dll in each project file. Because, each project has reference to project Adapter which will automatically copy Riosock.dll.

Fix SocketStream.ReadByte() to release unreadable cache

---

cpp/Riosock/Riosock.cpp
cpp/Riosock/Riosock.h
csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Interop/Ipc/JvmBridge.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/ByteBufChunk.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/ByteBufPool.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/DefaultSocketWrapper.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/ISocketWrapper.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/RioNative.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/RioSocketWrapper.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/SaeaSocketWrapper.cs
csharp/Adapter/Microsoft.Spark.CSharp/Network/SocketStream.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StreamingContextIpcProxy.cs
csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML
csharp/Adapter/documentation/Mobius_API_Documentation.md
csharp/AdapterTest/AccumulatorTest.cs
csharp/AdapterTest/ByteBufPoolTest.cs
csharp/AdapterTest/Mocks/MockSparkContextProxy.cs
csharp/AdapterTest/SocketWrapperTest.cs
csharp/AdapterTest/TestWithMoqDemo.cs
csharp/Worker/Microsoft.Spark.CSharp/MultiThreadWorker.cs
csharp/Worker/Microsoft.Spark.CSharp/TaskRunner.cs
csharp/Worker/Microsoft.Spark.CSharp/Worker.cs
csharp/WorkerTest/WorkerTest.cs
scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala

There are random failures on Worker.WriteOutput() with socket error 10022 (An invalid argument was supplied). The reason of the error is because the RioSocketWrapper pass the managed buffer to native buffer and call native code to send the data too many. 
This change is to modify SocketStream.Write with a send data cache, so that to reduce the frequency of calling Riosocket send operation.

Fix error 10022 in Worker.WriteOutput() caused by RioSocket

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/PipelinedRDD.cs
csharp/Adapter/Microsoft.Spark.CSharp/Services/DefaultLoggerService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Services/ILoggerService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Services/Log4NetLoggerService.cs
csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML
csharp/Worker/Microsoft.Spark.CSharp/Worker.cs

Currently, the CSharpWorkerFunc stacktrace looks like the same with exception stack trace. It is really confusing to users. This change is to improve CSharpWorker logging to make CSharpWorkerFunc stacktrace looks like below:
[2016-08-31T18:42:36.1260640Z] [HEBIN-Z420] [Debug] [Worker]
------------------------ Printing stack trace of workerFunc for ** debugging ** ------------------------------
[STACK] Microsoft.Spark.CSharp.Core.CSharpWorkerFunc..ctor(Func`3 func)
[STACK] Microsoft.Spark.CSharp.Core.CSharpWorkerFunc..ctor(Func`3 func, String innerStackTrace)
[STACK] Microsoft.Spark.CSharp.Core.PipelinedRDD`1.MapPartitionsWithIndex[U1](Func`3 newFunc, Boolean preservesPartitioningParam)
[STACK] SelectionSensorsAgg.Program.<>c.<Main>b__35_6(RDD`1 rdd) in …

(Branch-1.6) Improve Worker logging to make CSharpWorkerFunc stacktrace clear

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/CSharpWorkerFunc.cs
csharp/Adapter/Microsoft.Spark.CSharp/Services/DefaultLoggerService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Services/ILoggerService.cs
csharp/Adapter/Microsoft.Spark.CSharp/Services/Log4NetLoggerService.cs
csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML
csharp/AdapterTest/ByteBufTest.cs
csharp/Worker/Microsoft.Spark.CSharp/Worker.cs

Currently, the CSharpWorkerFunc stacktrace looks like the same with exception stack trace. It is really confusing to users. This change is to improve CSharpWorker logging to make CSharpWorkerFunc stacktrace looks like below:
[2016-08-31T18:42:36.1260640Z] [HEBIN-Z420] [Debug] [Worker]
------------------------ Printing stack trace of workerFunc for ** debugging ** ------------------------------
[STACK] Microsoft.Spark.CSharp.Core.CSharpWorkerFunc..ctor(Func3 func) [STACK] Microsoft.Spark.CSharp.Core.CSharpWorkerFunc..ctor(Func3 func, String innerStackTrace)
[STACK] Microsoft.Spark.CSharp.Core.PipelinedRDD1.MapPartitionsWithIndex[U1](Func3 newFunc, Boolean preservesPartitioningParam)
[STACK] SelectionSensorsAgg.Program.<>c.b__35_6(RDD1 rdd) in …

Improve Worker logging to make CSharpWorkerFunc stacktrace clear

---

build/build.sh
build/localmode/run-samples.sh

This is a unix-specific shell script and should only use unix path separators. When executed on a unix system, the resulting path names are incorrect. For example:
`[run-samples.sh]
SPARKCLR_EXT_JARS=/home/dwnichols/Mobius/build/localmode/../runtime\dependencies\spark-csv_2.10-1.3.0.jar,/home/dwnichols/Mobius/build/localmode/../runtime\dependencies\commons-csv-1.1.jar`

Windows path separators used in run-samples.sh

---

.gitignore
csharp/Perf/Microsoft.Spark.CSharp/FreebaseDeletionsBenchmark.cs
csharp/Perf/Microsoft.Spark.CSharp/PerfBenchmark.csproj
csharp/Perf/Microsoft.Spark.CSharp/Program.cs
python/perf/FreebaseDeletionsBenchmark.py
python/perf/PerfBenchmark.py
python/perf/spark-python-perf.py
scala/perf/src/main/com/microsoft/spark/csharp/FreebaseDeletionsBenchmark.scala
scala/perf/src/main/com/microsoft/spark/csharp/PerfBenchmark.scala

Besides normal spark-submit , there's a convenient way use https://github.com/qualiu/testMobius , cluster examples as following:
d:\msgit\lqmMobius\testMobius\scripts\perf\submit-python-perf-test.bat d:\msgit\lqmMobius\python\perf 1 hdfs:///perf/data/deletions/deletions.csv-00000-of-00020
D:\msgit\lqmMobius\testMobius\scripts\perf\submit-scala-perf-test.bat  d:\msgit\lqmMobius\scala\perf  1 hdfs:///perf/data/deletions/deletions.csv-00000-of-00020
D:\msgit\lqmMobius\testMobius\scripts\perf\submit-mobius-perf-test.bat d:\msgit\lqmMobius\csharp\perf 1 hdfs:///perf/data/deletions/deletions.csv-00000-of-00020

Add Python performance benchmark test; Add usage and example and RIOSocket option support for C# benchmark; Update Scala benchmark.

---

csharp/Perf/Microsoft.Spark.CSharp/PerfBenchmark.csproj

cp -uv is run on OSX, but the option -u is not available in OSX, so I'm using the copy task which works cross operating system. It lets msbuild take care of operation system copying functionality.

Use copy task instead of OS commands so it builds on OSX

---

scripts/sparkclr-submit.sh

Sparks Jar ClassPath doesn't work in in linux because of back slash.  This fixes that.

use forward slash to work in linux/osx

---

csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs
scala/src/main/org/apache/spark/api/csharp/CSharpRDD.scala

Adding "yarn" as a valid value for master config - this is allowed in Spark 2.0
Fixing the issues in launching CSharpWorker.exe in YARN clusters - introduced during Spark 2.0 upgrade

fixing the issue in YARN clusters introduced during Spark 2.0 upgrade

---

build/localmode/RunSamples.cmd
build/localmode/downloadtools.ps1
build/localmode/run-samples.sh

(1) Fix outdated version of Spark binary distributions from Apache being used in Mobius builds.
- Specifically, Spark `2.0.0` is no longer available as a binary `.tgz` distribution from Apache Software Foundation Distribution server.
http://www.us.apache.org/dist/spark/
- Only versions `1.6.2` and `2.0.1` of Spark binary distributions are available for download from the Apache Distribution server now.
```
http://www.us.apache.org/dist/spark/
[DIR] spark-1.6.2/            2016-06-25 07:38    -
[DIR] spark-2.0.1/            2016-10-04 17:26    -
```
- This Pull Request changes the Spark version defaults in Mobius download scripts to match what is the currently available from Apache:
`1.6.1` -> `1.6.2` and `2.0.0` -> `2.0.1`
(2) Add guard code to check that Download-File function got a real …

Fix Spark version build problems

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/PairRDDFunctions.cs
csharp/AdapterTest/PairRDDTest.cs

ReduceByKey fails with a NPE if the value type is a reference type, even if there are no null values in the PairRDD. 
The reason of the error is that ReduceByKey calls CombineByKey with a seed generator of () => default(V). When the value is a reference type, this seed value is null. The lambda will try to accumulate the values to this seed value of null. A unit test was added to demonstrate this behavior.
The fix not only avoids NPE errors, but it is also more efficient, because it calls the lambda of the ReduceByKey for actual value pairs only.
This behavior is also in line with the Scala and Java execution: ReduceByKey doesn't call the lambda with the default value of the data type.

Fix ReduceByKey failure when the value type is a reference type

---

csharp/Adapter/Microsoft.Spark.CSharp/Streaming/PairDStreamFunctions.cs
csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML
csharp/AdapterTest/DStreamTest.cs

This fix depends on #605, and is related to #602

DStream ReduceByKey will fail with reference types

---

csharp/Adapter/Microsoft.Spark.CSharp/Core/StatusTracker.cs
csharp/Adapter/Microsoft.Spark.CSharp/Proxy/Ipc/StatusTrackerIpcProxy.cs
csharp/Adapter/documentation/Microsoft.Spark.CSharp.Adapter.Doc.XML
csharp/Adapter/documentation/Mobius_API_Documentation.md
csharp/AdapterTest/StatusTrackerTest.cs

Change the interface of SparkJobInfo to be more inline with the scala implementation.

Expose JobExecutionStatus in SparkJobInfo as an enum

---

build/localmode/downloadtools.ps1

A more permanent solution here needs to be found so that
we do not need to update this link. In the meantime, this
will unblock users from successfully building

Update TarTool direct link.

---

notes/running-mobius-app.md

It was pointing to SparkClrPi.exe instead of SparkClrWordCount.exe

WordCount Example (Batch) exe path correction

---

csharp/Adapter/Microsoft.Spark.CSharp/Sql/Functions.cs

int is not valid type in spark, so fixed it to integer

Fixed integer Data type issue for UDF

---

README.md

This change urlencodes the ?text= parameter so that the button can be used as intended.
I've also noticed that the issue stats buttons for pull request / issues are broken. 
I've left this untouched, so that other Hacktoberfest participants may PR against it, if permissible (for removal/replacement/triage).

README: Twitter badge fix
